# Selecciona el template...
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Se elige el título del sitio...
title: [Edward Alonso Villamil Avellaneda]
# Se elige la descripción del sitio...
description: [Professional Profile and Curriculum Vitae]

# Se habilita la descarga de los códigos fuente...
show_downloads: true
