remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Edward Alonso Villamil Avellaneda]
description: [Professional Profile and Curriculum Vitae]

show_downloads: true
